INSERT INTO "public".affiliation( id, nom ) VALUES ( default, 'Cnaps');
INSERT INTO "public".affiliation( id, nom ) VALUES ( default, 'Ostie');
INSERT INTO "public".affiliation( id, nom ) VALUES ( default, 'Cnaps');
INSERT INTO "public".affiliation( id, nom ) VALUES ( default, 'Ostie');
INSERT INTO "public".filiere( id, nom ) VALUES ( default, 'Design');
INSERT INTO "public".filiere( id, nom ) VALUES ( default, 'Info');
INSERT INTO "public".filiere( id, nom ) VALUES ( default, 'Compta');
INSERT INTO "public".filiere( id, nom ) VALUES ( default, 'Managment');
INSERT INTO "public".fonction( id, nom ) VALUES ( default, 'F1');
INSERT INTO "public".fonction( id, nom ) VALUES ( default, 'HC');
INSERT INTO "public".fonction( id, nom ) VALUES ( default, 'F1');
INSERT INTO "public".fonction( id, nom ) VALUES ( default, 'HC');
INSERT INTO "public".grade( id, nom ) VALUES ( default , 'DTS');
INSERT INTO "public".grade( id, nom ) VALUES ( default , 'LICENSE');
INSERT INTO "public".grade( id, nom ) VALUES ( default , 'MASTER');
INSERT INTO "public".grade( id, nom ) VALUES ( default , 'DOCTORAT');
INSERT INTO "public".poste( id, nom, starting_salary ) VALUES ( default, 'Poste 1', 20000.0);
INSERT INTO "public".poste( id, nom, starting_salary ) VALUES ( default, 'Poste 2', 20000.0);
INSERT INTO "public".poste( id, nom, starting_salary ) VALUES ( default, 'Poste 3', 20000.0);
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Diana');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Sava');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Itasy');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Analamanga');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Vakinankaratra');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Bongolava');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Sofia');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Boeny');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Betsiboka');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Melaky');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Alaotra-Mangoro');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Atsinanana');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Analanjirofo');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Ambatosoa');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Amoron i Mania');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Vatovavy');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Fitovinany');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Haute Matsiatra');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Atsimo-Atsinanana');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Ihorombe');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Menabe');
INSERT INTO "public".region( id, nom ) VALUES ( default , 'Atsimo-Andrefana');
INSERT INTO "public".service( id, nom ) VALUES ( default , 'security');
INSERT INTO "public".service( id, nom ) VALUES ( default , 'finance');
INSERT INTO "public".service( id, nom ) VALUES ( default , 'information system');
INSERT INTO "public".service( id, nom ) VALUES ( default , 'marketing');
INSERT INTO "public".service( id, nom ) VALUES ( default , 'production');
INSERT INTO "public".service( id, nom ) VALUES ( default , 'sales');
INSERT INTO "public".service( id, nom ) VALUES ( default , 'customer service');
INSERT INTO "public".service( id, nom ) VALUES ( default , 'administration');
INSERT INTO "public".service( id, nom ) VALUES ( default , 'maintenance');
INSERT INTO "public".service( id, nom ) VALUES ( default , 'research');
INSERT INTO "public".service( id, nom ) VALUES ( default , 'planning');
INSERT INTO "public".service( id, nom ) VALUES ( default , 'quality assurance');
INSERT INTO "public".service( id, nom ) VALUES ( default , 'driving');
-- INSERT INTO "public".personnel( id, idposte, idservice, nom, prenom, dtn, dtembauche, idfonction ) VALUES ( 7, 3, 1, 'PN1', 'PN1', '1990-01-01', '2020-01-01', 1);
-- INSERT INTO "public".personnel( id, idposte, idservice, nom, prenom, dtn, dtembauche, idfonction ) VALUES ( 8, 4, 2, 'PN2', 'PN2', '1998-08-08', '2022-02-02', 2);
