INSERT INTO "public".affiliation( id, nom ) VALUES ( 1, 'Cnaps');
INSERT INTO "public".affiliation( id, nom ) VALUES ( 2, 'Ostie');
INSERT INTO "public".affiliation( id, nom ) VALUES ( 3, 'Cnaps');
INSERT INTO "public".affiliation( id, nom ) VALUES ( 4, 'Ostie');
INSERT INTO "public".annonce( id, idbesoinservice ) VALUES ( 1, 1);
INSERT INTO "public".cv( id, adresse, cin, email, nom, prenom, sexe, sm, tel ) VALUES ( 1, '1', '100110010', '', 'ANDRIANAIVOSOA ', 'Johan Anjaratiana ', 'male', 'married', '');
INSERT INTO "public".filiere( id, nom ) VALUES ( 1, 'Design');
INSERT INTO "public".filiere( id, nom ) VALUES ( 2, 'Info');
INSERT INTO "public".filiere( id, nom ) VALUES ( 3, 'Compta');
INSERT INTO "public".filiere( id, nom ) VALUES ( 4, 'Managment');
INSERT INTO "public".fonction( id, nom ) VALUES ( 1, 'F1');
INSERT INTO "public".fonction( id, nom ) VALUES ( 2, 'HC');
INSERT INTO "public".fonction( id, nom ) VALUES ( 3, 'F1');
INSERT INTO "public".fonction( id, nom ) VALUES ( 4, 'HC');
INSERT INTO "public".grade( id, nom ) VALUES ( 1, 'DTS');
INSERT INTO "public".grade( id, nom ) VALUES ( 2, 'LICENSE');
INSERT INTO "public".grade( id, nom ) VALUES ( 3, 'MASTER');
INSERT INTO "public".grade( id, nom ) VALUES ( 4, 'DOCTORAT');
INSERT INTO "public".poste( id, nom, starting_salary ) VALUES ( 1, 'Poste 1', 20000.0);
INSERT INTO "public".poste( id, nom, starting_salary ) VALUES ( 2, 'Poste 2', 20000.0);
INSERT INTO "public".poste( id, nom, starting_salary ) VALUES ( 3, 'Poste 3', 20000.0);
INSERT INTO "public".question( id, question ) VALUES ( 1, 'What are you looking for ?');
INSERT INTO "public".questionannonce( date_question_annonce, id, idannonce, idquestion ) VALUES ( '2023-10-22', 1, 1, 1);
INSERT INTO "public".questionreponse( id, idquestion, reponse, status ) VALUES ( 1, 1, 'No', 'false');
INSERT INTO "public".questionreponse( id, idquestion, reponse, status ) VALUES ( 2, 1, 'Yes', 'true');
INSERT INTO "public".region( id, nom ) VALUES ( 1, 'Diana');
INSERT INTO "public".region( id, nom ) VALUES ( 2, 'Sava');
INSERT INTO "public".region( id, nom ) VALUES ( 3, 'Itasy');
INSERT INTO "public".region( id, nom ) VALUES ( 4, 'Analamanga');
INSERT INTO "public".region( id, nom ) VALUES ( 5, 'Vakinankaratra');
INSERT INTO "public".region( id, nom ) VALUES ( 6, 'Bongolava');
INSERT INTO "public".region( id, nom ) VALUES ( 7, 'Sofia');
INSERT INTO "public".region( id, nom ) VALUES ( 8, 'Boeny');
INSERT INTO "public".region( id, nom ) VALUES ( 9, 'Betsiboka');
INSERT INTO "public".region( id, nom ) VALUES ( 10, 'Melaky');
INSERT INTO "public".region( id, nom ) VALUES ( 11, 'Alaotra-Mangoro');
INSERT INTO "public".region( id, nom ) VALUES ( 12, 'Atsinanana');
INSERT INTO "public".region( id, nom ) VALUES ( 13, 'Analanjirofo');
INSERT INTO "public".region( id, nom ) VALUES ( 14, 'Ambatosoa');
INSERT INTO "public".region( id, nom ) VALUES ( 15, 'Amoron i Mania');
INSERT INTO "public".region( id, nom ) VALUES ( 16, 'Vatovavy');
INSERT INTO "public".region( id, nom ) VALUES ( 17, 'Fitovinany');
INSERT INTO "public".region( id, nom ) VALUES ( 18, 'Haute Matsiatra');
INSERT INTO "public".region( id, nom ) VALUES ( 19, 'Atsimo-Atsinanana');
INSERT INTO "public".region( id, nom ) VALUES ( 20, 'Ihorombe');
INSERT INTO "public".region( id, nom ) VALUES ( 21, 'Menabe');
INSERT INTO "public".region( id, nom ) VALUES ( 22, 'Atsimo-Andrefana');
INSERT INTO "public".reponsetest( date_test, point, id, idannonce, idcv ) VALUES ( '2023-10-22', 100.0, 2, 1, 1);
INSERT INTO "public".service( id, nom ) VALUES ( 1, 'security');
INSERT INTO "public".service( id, nom ) VALUES ( 2, 'finance');
INSERT INTO "public".service( id, nom ) VALUES ( 3, 'information system');
INSERT INTO "public".service( id, nom ) VALUES ( 4, 'marketing');
INSERT INTO "public".service( id, nom ) VALUES ( 5, 'production');
INSERT INTO "public".service( id, nom ) VALUES ( 6, 'sales');
INSERT INTO "public".service( id, nom ) VALUES ( 7, 'customer service');
INSERT INTO "public".service( id, nom ) VALUES ( 8, 'administration');
INSERT INTO "public".service( id, nom ) VALUES ( 9, 'maintenance');
INSERT INTO "public".service( id, nom ) VALUES ( 10, 'research');
INSERT INTO "public".service( id, nom ) VALUES ( 11, 'planning');
INSERT INTO "public".service( id, nom ) VALUES ( 12, 'quality assurance');
INSERT INTO "public".service( id, nom ) VALUES ( 13, 'driving');
INSERT INTO "public".type_hs ( id, nom, pourcentage) VALUES ( default, '8 premieres heure', 30 );
INSERT INTO "public".type_hs ( id, nom, pourcentage) VALUES ( default, '+ de 8 heure', 50 );
INSERT INTO "public".type_hs ( id, nom, pourcentage) VALUES ( default, 'Week-end', 40 );
INSERT INTO "public".type_hs ( id, nom, pourcentage) VALUES ( default, 'Jour ferier', 100 );
INSERT INTO "public".type_hs ( id, nom, pourcentage) VALUES ( default, 'Nuit', 30 );