import * as FlatColor from "react-icons/fc";
import { GiPayMoney } from "react-icons/gi";

export const SidePanelContent = [
  // {
  //   title: "Dashboard",
  //   type: "nav-item",
  //   icon: <BoxIcon.BiPieChartAlt2 />
  // },
  {
    title: "Department",
    type: "menu-title",
    onItemClick: () => {},
    onlyAdmin: false,
  },
  // {
  //   title: "All department",
  //   type: "nav-item",
  //   icon: <FlatColor.FcDepartment />,
  //   path: "department/all-department",
  //   onItemClick: () => {},
  // },
  {
    title: "Needs",
    type: "nav-item",
    icon: <FlatColor.FcSettings />,
    path: "/department/needs",
    onItemClick: () => {},
    onlyAdmin: false,
  },
  // {
  //   title: "Criteria needs",
  //   type: "nav-item",
  //   icon: <FlatColor.FcSettings />,
  //   path: "/offre/critere",
  //   onItemClick: () => {},
  // },
  {
    title: "Forms",
    type: "menu-title",
    onItemClick: () => {},
    onlyAdmin: false,
  },
  {
    title: "QCM",
    type: "nav-item",
    path: "/question/Test/questionanswer",
    icon: <FlatColor.FcDocument />,
    onItemClick: () => {},
    onlyAdmin: false,
  },
  {
    title: "Question de test",
    type: "nav-item",
    path: "/question/Test/questionaddy",
    icon: <FlatColor.FcDocument />,
    onItemClick: () => {},
    onlyAdmin: false,
  },
  {
    title: "Employment",
    type: "nav-item",
    path: "/employment/confirm",
    icon: <FlatColor.FcDocument />,
    onItemClick: () => {},
    onlyAdmin: false,
  },
  {
    title: "List",
    type: "menu-title",
    onItemClick: () => {},
    onlyAdmin: true,
  },
  {
    title: "Resume",
    type: "nav-item",
    path: "/list/resume",
    icon: <FlatColor.FcKindle />,
    onItemClick: () => {},
    onlyAdmin: true,
  },
  {
    title: "Inerviewer list",
    type: "nav-item",
    path: "/list/able-to-interview",
    icon: <FlatColor.FcKindle />,
    onItemClick: () => {},
    onlyAdmin: true,
  },
  {
    title: "Management",
    type: "menu-title",
    onItemClick: () => {},
    onlyAdmin: false,
  },
  {
    title: "Services",
    type: "nav-item",
    path: "/management/services",
    icon: <FlatColor.FcServices />,
    onItemClick: () => {},
    onlyAdmin: false,
  },
  {
    title: "Sectors",
    type: "nav-item",
    path: "/management/sectors",
    icon: <FlatColor.FcInspection />,
    onItemClick: () => {},
    onlyAdmin: false,
  },
  {
    title: "Grades",
    type: "nav-item",
    path: "/management/grades",
    icon: <FlatColor.FcGraduationCap />,
    onItemClick: () => {},
    onlyAdmin: false,
  },
  {
    title: "Positions",
    type: "nav-item",
    path: "/management/positions",
    icon: <FlatColor.FcPodiumWithoutSpeaker />,
    onItemClick: () => {},
    onlyAdmin: false,
  },
  {
    title: "Regions",
    type: "nav-item",
    path: "/management/regions",
    icon: <FlatColor.FcRegisteredTrademark />,
    onItemClick: () => {},
    onlyAdmin: false,
  },
  {
    title: "Heure supp",
    type: "nav-item",
    path: "/management/heure-supp",
    icon: <FlatColor.FcRegisteredTrademark />,
    onItemClick: () => {},
    onlyAdmin: false,
  },
  {
    title: "Extra",
    type: "menu-title",
    onItemClick: () => {},
    onlyAdmin: true,
  },
  {
    title: "Fiche de poste",
    type: "nav-item",
    path: "/embauche/fichedeposte",
    icon: <FlatColor.FcKindle />,
    onItemClick: () => {},
    onlyAdmin: true,
  },
  {
    title: "Contract",
    type: "nav-item",
    path: "/embauche/contrat",
    icon: <FlatColor.FcApproval />,
    onItemClick: () => {},
    onlyAdmin: true,
  },
  {
    title: "Wage slip",
    type: "nav-item",
    path: "/wage/wageslip",
    icon: <FlatColor.FcApproval />,
    onItemClick: () => {},
    onlyAdmin: true,
  },
  {
    title: "Conge",
    type: "nav-item",
    path: "/conge",
    icon: <FlatColor.FcApproval />,
    onItemClick: () => {},
    onlyAdmin: true,
  },
  // {
  //   title: "Form resume",
  //   type: "nav-item",
  //   path: "/test/resume",
  //   icon: <FlatColor.FcKindle />,
  //   onItemClick: () => {},
  // },
  {
    title: "Payroll",
    type: "nav-item",
    path: "/pay/payroll",
    icon: <GiPayMoney />,
    onItemClick: () => {},
    onlyAdmin: true,
  },

  // {
  //   title: "Annonce",
  //   type: "nav-item",
  //   path: "/offre/annonce",
  //   icon: <FlatColor.FcDocument />,
  //   onItemClick: () => {},
  // },
];
